[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
bytecode_hash = "none"
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]
auto_detect_remappings = true
gas_reports = ["*"]

remappings = ['@aave/core-v3/=lib/protocol-v3',
            '@openzeppelin=lib/openzeppelin-contracts',
            '@api3/contracts=lib/contracts/contracts',
            '@uniswap/v3-periphery=node_modules/@uniswap/v3-periphery',
            '@uniswap/v3-core=node_modules/@uniswap/v3-core',
            '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
            '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
            '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
            '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
            '@solidity-bytes-utils=lib/solidity-bytes-utils',

    ]


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options




