[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
remappings = ['@aave/core-v3/=lib/protocol-v3',
            '@openzeppelin=lib/openzeppelin-contracts',
            '@api3/contracts=lib/contracts/contracts',
            '@uniswap/v3-periphery=node_modules/@uniswap/v3-periphery',
            '@uniswap/v3-core=node_modules/@uniswap/v3-core',
            '@chainlink/contracts=lib/chainlink-brownie-contracts/contracts',
            '@layerzerolabs/oft-evm/=lib/devtools/packages/oft-evm/',
            '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
            '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
            '@solidity-bytes-utils=lib/solidity-bytes-utils',

    ]
[etherscan]
optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}" }

[Invariant]
runs = 128
depth = 128
fail_on_revert = true




# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
